spring:
  datasource:
    url: jdbc:mysql://0.0.0.0
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 0.0.0.0
    port: 6379
    password: 123456
